# Generated by Django 5.2.7 on 2025-10-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='ano_fabricacao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
